---
# tasks file for ans_ad_domain_role
- name: Verify AD Membership
  include_tasks: ad_state_linux.yml

- name: Tasks for joining AD
  block:
    - name: Set OS-specific variables
      include_vars: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"

    - name: Install packages required to join AD
      package: 
        name: "{{ item }}"
        state: present
      with_items: 
        - "{{ pkgs }}"

    - name: Join AD realm via adcli (creating AD computer account and updating /etc/krb5.keytab)
      shell: echo '{{ ad_user_password }}' | adcli join --stdin-password -D {{ ad_domain_fqdn | lower }} -U {{ ad_user_name | lower }} --domain-ou={{ ad_computer_ou }} --os-name={{ ansible_distribution }} --os-version={{ ansible_distribution_major_version }}

    - name: Configure sssd.conf
      template:
        src: sssd.j2
        dest: /etc/sssd/sssd.conf
        owner: root
        group: root
        mode: 0600

    - name: Configure krb5.conf
      template:
        src: "{{ ansible_os_family }}/krb5.j2"
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: 0644

    - name: Tasks for Debian based OS
      block:
        - name: Configure pam/sshd to use sssd
          shell: sudo pam-auth-update --enable mkhomedir
      when: ansible_os_family == 'Debian'

    - name: Tasks for RedHat based OS
      block:
        - name: Configure pam/sshd to use sssd
          shell: authselect select sssd with-mkhomedir --force
        
        - name: Enable oddjobd
          shell: systemctl enable oddjobd
      when: ansible_os_family == 'RedHat'

    - name: Reboot the machine with all defaults options
      reboot:
  when: not ad_joined
