---
# tasks file for ans_ad_domain_role | Windows
# - name: Include OS-specific variables.
#   include_vars: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"

- name: Join AD (creating AD computer account and updating /etc/krb5.keytab)
  win_domain_membership: 
    dns_domain_name: "{{ ad_domain_fqdn | lower }}"
    hostname: "{{ ansible_hostname | upper }}"
    domain_admin_user: "{{ ad_user_name | lower }}"
    domain_admin_password: "{{ ad_user_password }}"
    domain_ou_path: "{{ ad_computer_ou }}"
    state: present
  register: domain_state

# - name: Create server specific admin AD group
#   win_domain_group:
#     name: TU-ServerAccess-({{ ansible_hostname | upper }})-LocalGroups-Administrators
#     scope: global
#     path: {{ ad_admin_adhoc }}

- name: Reboot server
  win_reboot:
  when: domain_state.reboot_required